server.port=5000
spring.datasource.url=jdbc:mysql:/localhost:3306/railway
spring.datasource.username=root
spring.datasource.password=RVLHbpgklilpeOGmeWIWbjUqcgxMYOKb
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
spring.sql.show-sql=true
spring.datasource.hikari.connection-init-sql=SET SESSION sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'


# Flyway Configuration
spring.flyway.enabled=false

