server.port=${PORT:5000}
# 1. Database URL
# Logic: If the env variable RDS_ENDPOINT exists, use it.
# If NOT (like on your laptop), default to localhost:3306/federaldb
# Localhost:3307 is set up to do ssh tunneling via a jumpbox machine
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
# 3. Password
# Logic: Use DB_PASSWORD env var, or default to 'password'
spring.datasource.password=${MYSQLPASSWORD}
#spring.datasource.password=koch14
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
spring.sql.show-sql=true
# Set SQL mode per connection (removes ONLY_FULL_GROUP_BY)
spring.datasource.hikari.connection-init-sql=SET SESSION sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'


# Flyway Configuration
spring.flyway.enabled=false

