server.port=5000
spring.datasource.url=jdbc:mysql://localhost:3307/transit
#spring.datasource.url=jdbc:mysql://federal-transit-private.cfs8yemy659e.us-east-1.rds.amazonaws.com:3306/transit?sessionVariables=sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
#spring.datasource.url=jdbc:mysql://federal-transit-3.cdtvaqwslfid.us-east-1.rds.amazonaws.com:3306/transit
#spring.datasource.url=jdbc:mysql://database-2.cdtvaqwslfid.us-east-1.rds.amazonaws.com:3306/transit
spring.datasource.username=root
spring.datasource.password=koch2357
#spring.datasource.password=koch14
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
spring.sql.show-sql=true
